#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=config.sh
source "${SCRIPT_DIR}/config.sh"
# shellcheck source=minio.env
source "${SCRIPT_DIR}/minio.env"

CT_IP="${IP%%/*}"
ENDPOINT="http://${CT_IP}:9000"

if ! command -v mc &>/dev/null; then
  echo "Installing mc on Proxmox host..."
  curl -fsSL https://dl.min.io/client/mc/release/linux-amd64/mc \
    -o /usr/local/bin/mc
  chmod +x /usr/local/bin/mc
fi

echo "Configuring mc alias..."
mc alias set minio-local "${ENDPOINT}" "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}"

echo "Creating bucket ${BUCKET}..."
mc mb --ignore-existing "minio-local/${BUCKET}"
mc version enable "minio-local/${BUCKET}" || true

cat > "${SCRIPT_DIR}/terraform-backend.env" <<EOF
# Generated by bootstrap-bucket.sh — do not commit
AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
TF_BACKEND_ENDPOINT=${ENDPOINT}
TF_BACKEND_BUCKET=${BUCKET}
TF_BACKEND_KEY=proxmox/kubernetes/terraform.tfstate
EOF
chmod 600 "${SCRIPT_DIR}/terraform-backend.env"

echo "Wrote ${SCRIPT_DIR}/terraform-backend.env"